name: Build UWP App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    env:
      Solution_Name: WinGoMapsX.sln
      Configuration: Release
      Platform: x64
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
      
    - name: Restore with MSBuild
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:RestorePackagesConfig=true
      
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:AppxBundlePlatforms="x64" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxPackageSigningEnabled=false
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WinGoMapsX-Package
        path: |
          WinGoMapsX/AppPackages/**
